services:
  katou-megumi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "cmd/app/main.go"]
    networks:
      - katou-megumi-network

networks:
  katou-megumi-network:
    driver: bridge
